tiled: Support tile flipping flags
not-fl3/macroquad pull request #258
Opened 2021-07-18 22:14 UTC by septum

Based from this [documentation reference](https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#tile-flipping).

Beware: code may be ugly and unidiomatic.

2022-06-21 09:55 UTC, vdrn commented on tiled/src/lib.rs
> +                        -90. * f32::consts::PI / 180.
The issue is here. We need to multiply by 90 instead of -90.

2022-06-21 10:03 UTC, vdrn requested changes
This feature requires fixing rotation code. At line 121@tiled/src/lib.rs we should multiply by `90` instead of `-90`.

2022-07-16 15:02 UTC, vdrn commented
> This feature requires fixing rotation code. At line 121@tiled/src/lib.rs we should multiply by `90` instead of `-90`.

Please disregard my previous comment.


Currrently this works for me, though I'm sure there must be  a simpler method to do this:
```
flip_x: (flags.horizontally
    && (!flags.antidiagonally || (flags.vertically && flags.antidiagonally)))
    || (!flags.horizontally && flags.antidiagonally && !flags.vertically),  
    
flip_y: flags.vertically && !flags.antidiagonally && !flags.horizontally,  

rotation: if flags.antidiagonally {  
    if !flags.horizontally {  
        -f32::consts::PI / 2.0  
    } else {  
        f32::consts::PI / 2.0  
    }  
} else {
    0.
}
```

2023-02-26 23:12 UTC, septum commented
I'll close this now.

2023-02-26 23:12 UTC, closed without merging