New Example - Simple Physics Simulation (Confetti)
not-fl3/macroquad pull request #874
Opened 2024-12-31 13:52 UTC by Andrew-McCall

PR to add an interactive 2D physics example to the example games. 

Confetti is a super simple simulation where balls fall and collide with each other. Players Click to spawn new balls.

You can find my ReadMe with more instructions and description. Only uses std:u8 (Color) and Macroquad. 
[Confetti Repo](https://github.com/Andrew-McCall/MacroquadConfetti?tab=readme) (Written by me 31/12/24 and MIT)
A fun example I made to compare rust to a friend's python code. You can rename it as you see if; I thought the balls looked like confetti when there was more than 500 (Runs smoothly with 5k).

2025-01-03 20:29 UTC, cyrgani commented
Please run `cargo fmt` on your code for consistent style.

2025-01-08 21:03 UTC, Andrew-McCall commented
Apologies for the delay, 
Ran `cargo fmt`

Thanks!

2025-01-08 22:42 UTC, cyrgani requested changes
Left some suggestions to remove `unsafe` and a few other things.

2025-01-08 22:42 UTC, cyrgani commented on examples/confetti.rs
> +extern crate micromath;
This crate is not part of the macroquad dependency tree. I tried running the program without this line and the line below and it worked fine though, so this should be removable.

2025-01-08 22:42 UTC, cyrgani commented on examples/confetti.rs
> +static mut BALL_ID: usize = 0;
You can use an `AtomicUsize` her to avoid using the `unsafe` `static mut`:
`static BALL_ID: AtomicUsize = AtomicUsize::new(0);`

2025-01-08 22:42 UTC, cyrgani commented on examples/confetti.rs
> +        }
With an atomic as above, this is just `let id = BALL_ID.fetch_add(1, Ordering::SeqCst);`.

2025-01-08 22:42 UTC, cyrgani commented on examples/confetti.rs
> +            let skip = (BALL_ID / 1000).max(8);
`BALL_ID.load(Ordering::SeqCst)` instead of `unsafe`.

2025-01-08 22:42 UTC, cyrgani commented on examples/confetti.rs
> +            }
ditto

2025-01-08 22:42 UTC, cyrgani commented on examples/confetti.rs
> +            if BALL_ID == 0 {
ditto

2025-01-08 22:42 UTC, cyrgani commented on examples/confetti.rs
> +                (random as usize * 47 % 255) as u8,
`random` is already an `usize` though?

2025-01-16 20:25 UTC, Andrew-McCall commented
Thanks. I updated my code on my main and i pulled it over after fmt.
but left my testing and other software rot in it. My bad.

2025-01-16 20:25 UTC, closed without merging